### ISSUE TITLE
[BE] 음악 관련 api

### ISSUE THREAD

**Issue by Fishphobiagg** [Fishphobiagg/Muvie#16]
### To-do

- [x] 플레이리스트 추가/제거 api
- [x] 음악 좋아요 api
- [x] 음악 정보 검색 api
