### ISSUE TITLE
[BE]프로필 조회 속도 개선

### ISSUE THREAD

**Issue by Fishphobiagg** [Fishphobiagg/Muvie#18]
### Description
프로필 조회 api 속도 개선을 위한 이슈

### To-do

- [x] Django Debug Toolbar 적용
- [x] 기존 방법 속도 및 TestSerializer 속도 비교
- [x] 우수한 방법 채택
