### ISSUE TITLE
[BE] 영화 API 구현

### ISSUE THREAD

**Issue by Fishphobiagg** [Fishphobiagg/Muvie#3]
### Description

영화 데이터 관련 API 구현

### To-do

- [x] 영화 데이터베이스 모델링
- [x] 요청된 영화 정보 조회 API
- [x] 영화 정보 검색 api 구현
- [x] 영화 좋아요 api 구현
