### ISSUE TITLE
[FE] 취향 선택 페이지 구현

### ISSUE THREAD

**Issue by YeryunJung** [Fishphobiagg/Muvie#32]
### Description
추천에 활용할 사용자 취향 선택 페이지 구현

### To-do
- [x] 사용자 프로필 호출
- [x] 취향 데이터 서버로 전달
- [x] 회원가입 후 라우팅
- [x] 마이페이지 취향 재설정 구현
