### ISSUE TITLE
[FE] 페이지 라우팅

### ISSUE THREAD

**Issue by YeryunJung** [Fishphobiagg/Muvie#36]
### Description
페이지 라우팅

### To-do
- [x] 메인 페이지 프로필 버튼 (마이페이지, 로그아웃)
- [x] 비로그인시 로그인 모달 오픈
- [x] 로고 클릭시 메인페이지 이동
- [x] 회원가입후 로그인 이동
- [x] 검색 후 디테일 페이지 이동
